global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using CheckBox = System.Windows.Controls.CheckBox;
global using Button = System.Windows.Controls.Button;
global using Color = System.Windows.Media.Color;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using DataObject = System.Windows.DataObject;
global using DragEventArgs = System.Windows.DragEventArgs;
global using DragDropEffects = System.Windows.DragDropEffects;
global using IDataObject = System.Windows.IDataObject;
global using MessageBox = System.Windows.MessageBox;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Point = System.Windows.Point;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
